#!/usr/bin/env python3
"""Emit main/app/catalog_available_font_catalog.gen.hpp from bundled TTF cmap.

Each selectable font id is paired with its asset filename (same order as
FontFamily / GET availableFonts). `has_btc_symbol` is True iff the file
exists under --assets and cmap maps U+20BF. Missing files default to True
so sparse checkouts still compile; run after `regen.sh` for authoritative bits.

Invoked from tools/fonts/regen.sh after subsetting.
"""

from __future__ import annotations

import argparse
import os
import sys

# Order MUST match FontFamily (main/fonts_app.hpp) and kAvailableFontCatalog.
FONT_ROWS: list[tuple[str, str]] = [
    ("antonio", "Antonio.ttf"),
    ("oswald", "Oswald.ttf"),
    ("inter", "Inter.ttf"),
    ("sourceSerif", "SourceSerif.ttf"),
    ("merriweather", "Merriweather.ttf"),
    ("bitter", "Bitter.ttf"),
    ("atkinson", "Atkinson.ttf"),
    ("antonioSemiBold", "AntonioSemiBold.ttf"),
    ("antonioBold", "AntonioBold.ttf"),
    ("oswaldBold", "OswaldBold.ttf"),
    ("interBold", "InterBold.ttf"),
    ("sourceSerifBold", "SourceSerifBold.ttf"),
    ("merriweatherBold", "MerriweatherBold.ttf"),
    ("bitterBold", "BitterBold.ttf"),
    ("atkinsonBold", "AtkinsonBold.ttf"),
    # Single picker id for the Open Runde pair — probe the regular cut.
    ("openRunde", "OpenRunde.ttf"),
    ("roboto", "Roboto.ttf"),
    ("robotoBold", "RobotoBold.ttf"),
    ("notoSans", "NotoSans.ttf"),
    ("notoSansBold", "NotoSansBold.ttf"),
    ("ubuntu", "Ubuntu.ttf"),
    ("ubuntuBold", "UbuntuBold.ttf"),
    ("azeret", "Azeret.ttf"),
    ("azeretSemiBold", "AzeretSemiBold.ttf"),
]


def has_u20bf(path: str) -> bool:
    from fontTools.ttLib import TTFont

    cmap = TTFont(path).getBestCmap()
    return 0x20BF in cmap


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--assets", required=True, help="components/fonts/assets")
    ap.add_argument("--out", required=True, help="output .gen.hpp path")
    args = ap.parse_args()
    assets = args.assets

    rows: list[tuple[str, bool]] = []
    for font_id, fname in FONT_ROWS:
        path = os.path.join(assets, fname)
        if not os.path.isfile(path):
            rows.append((font_id, True))
            continue
        try:
            rows.append((font_id, has_u20bf(path)))
        except Exception as e:
            print(f"warn: {fname}: {e}", file=sys.stderr)
            rows.append((font_id, True))

    lines = [
        "// GENERATED by tools/fonts/gen_available_font_catalog.py — DO NOT EDIT.",
        "// Regenerate: python3 tools/fonts/gen_available_font_catalog.py --assets "
        "components/fonts/assets --out main/app/catalog_available_font_catalog.gen.hpp",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <string_view>",
        "",
        "namespace btclock::catalogs {",
        "",
        "struct AvailableFontCatalogEntry {",
        "  std::string_view id;",
        "  bool has_btc_symbol;",
        "};",
        "",
        f"inline constexpr std::size_t kAvailableFontCatalogCount = {len(rows)};",
        "",
        "inline constexpr std::array<AvailableFontCatalogEntry, kAvailableFontCatalogCount>",
        "    kAvailableFontCatalog{{",
    ]
    for fid, hbtc in rows:
        lit = "true" if hbtc else "false"
        lines.append(f'    {{"{fid}", {lit}}},')
    lines.append("}};")
    lines.append("")
    lines.append("}  // namespace btclock::catalogs")
    lines.append("")

    out_dir = os.path.dirname(args.out)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
