#!/usr/bin/env bash
# Regenerate every bundled font from its upstream source. Pulls Antonio
# and Oswald from Google Fonts main, DejaVu from the upstream 2.37
# release tarball, and re-converts SatoshiSymbol.ttf from the preserved
# `SatoshiSymbol_source.woff2`. Leaves all TTFs byte-identical if nothing
# upstream changed; otherwise the diff is the upstream glyph change.
#
# Run from anywhere — the script locates the assets dir via its own path.
# Requires: curl, tar, pyftsubset (`pip install fonttools`).
#
# After this, manually run `patch_satoshi_symbol.py` on the regenerated
# SatoshiSymbol.ttf if you want the (inert) U+E007 patch applied.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ASSETS="${HERE}/../../components/fonts/assets"
TMP="$(mktemp -d)"
trap 'rm -rf "${TMP}"' EXIT

if ! command -v pyftsubset >/dev/null; then
    echo "pyftsubset not found — pip install fonttools" >&2
    exit 127
fi

echo "→ Antonio (Google Fonts main)"
curl -sSL -o "${TMP}/Antonio.ttf" \
    "https://github.com/google/fonts/raw/main/ofl/antonio/Antonio%5Bwght%5D.ttf"
pyftsubset "${TMP}/Antonio.ttf" \
    "--unicodes=U+0020-007E,U+00A3,U+00A5,U+20AC" \
    "--drop-tables+=GPOS,GSUB,DSIG" \
    "--output-file=${ASSETS}/Antonio.ttf"

echo "→ Oswald (Google Fonts main)"
curl -sSL -o "${TMP}/Oswald.ttf" \
    "https://github.com/google/fonts/raw/main/ofl/oswald/Oswald%5Bwght%5D.ttf"
pyftsubset "${TMP}/Oswald.ttf" \
    "--unicodes=U+0020-007E" \
    "--drop-tables+=GPOS,GSUB,DSIG" \
    "--output-file=${ASSETS}/Oswald.ttf"

# OswaldBold is the same axis variable file instantiated at wght=700. The
# current in-tree copy was regenerated by hand; pyftsubset doesn't do the
# instance-pick on its own. Document here and skip — re-do via fonttools
# instancer if the bundled copy drifts.
echo "→ OswaldBold: skipped (manual wght=700 instance — see README)"

echo "→ DejaVu 2.37"
curl -sSL -o "${TMP}/dejavu.tar.bz2" \
    "https://downloads.sourceforge.net/project/dejavu/dejavu/2.37/dejavu-fonts-ttf-2.37.tar.bz2"
tar -xjf "${TMP}/dejavu.tar.bz2" -C "${TMP}"
pyftsubset "${TMP}/dejavu-fonts-ttf-2.37/ttf/DejaVuSans.ttf" \
    "--unicodes=U+0020-007E" \
    "--drop-tables+=GPOS,GSUB,DSIG" \
    "--output-file=${ASSETS}/DejaVu.ttf"
pyftsubset "${TMP}/dejavu-fonts-ttf-2.37/ttf/DejaVuSans-Bold.ttf" \
    "--unicodes=U+0020-007E" \
    "--drop-tables+=GPOS,GSUB,DSIG" \
    "--output-file=${ASSETS}/DejaVuBold.ttf"

echo "→ SatoshiSymbol (from preserved woff2)"
pyftsubset "${ASSETS}/SatoshiSymbol_source.woff2" \
    "--unicodes=U+E000-E00F" \
    "--drop-tables+=GPOS,GSUB,DSIG" \
    "--flavor=" \
    "--output-file=${ASSETS}/SatoshiSymbol.ttf"

echo "→ (optional) apply U+E007 padding patch"
echo "   ${HERE}/patch_satoshi_symbol.py ${ASSETS}/SatoshiSymbol.ttf"
echo
echo "Done. Sizes:"
wc -c "${ASSETS}"/*.ttf | awk '{printf "  %-40s %d B\n", $2, $1}'
