#!/usr/bin/env bash
# Regenerate every bundled font from its upstream source. Pulls Antonio,
# Oswald, Inter, Source Serif 4, Merriweather, Bitter, Atkinson
# Hyperlegible, Roboto, Noto Sans, and Ubuntu from their upstream
# GitHub repos, and re-converts SatoshiSymbol.ttf from the preserved
# `SatoshiSymbol_source.woff2`.
# Leaves all TTFs byte-identical if nothing upstream changed; otherwise
# the diff is the upstream glyph change.
#
# Run from anywhere — the script locates the assets dir via its own path.
# Requires: curl, pyftsubset (`pip install fonttools`).
#
# After this, manually run `patch_satoshi_symbol.py` on the regenerated
# SatoshiSymbol.ttf if you want the (inert) U+E007 patch applied.

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ASSETS="${HERE}/../../components/fonts/assets"
TMP="$(mktemp -d)"
trap 'rm -rf "${TMP}"' EXIT

if ! command -v pyftsubset >/dev/null; then
    echo "pyftsubset not found — pip install fonttools" >&2
    exit 127
fi

# Common subset: printable ASCII + £ ¥ € ₿. Every selectable family
# carries this range so the price screen's currency symbols work
# regardless of `fontName`. ₿ (U+20BF) is requested unconditionally;
# upstreams without the glyph silently drop it (see verify_btc_sign
# below for which families end up with it).
COMMON_UNICODES="U+0020-007E,U+00A3,U+00A5,U+20AC,U+20BF"

subset_full() {
    # $1=input ttf, $2=output ttf — use the canonical subset recipe
    # (drop layout tables, drop hinting, keep ASCII + £/¥/€/₿).
    pyftsubset "$1" \
        "--output-file=$2" \
        "--unicodes=${COMMON_UNICODES}" \
        "--ignore-missing-unicodes" \
        "--drop-tables+=GPOS,GSUB,DSIG" \
        "--layout-features=*" \
        "--no-hinting"
}

# Antonio and Oswald upstreams ship variable fonts. stb_truetype doesn't
# read fvar/gvar — instance to the chosen base weight first so the subset
# is a static font and the variable tables are dropped (gvar alone is
# ~11 KB).
echo "→ Antonio (Google Fonts main, instance wght=400)"
curl -sSL -o "${TMP}/Antonio-VF.ttf" \
    "https://github.com/google/fonts/raw/main/ofl/antonio/Antonio%5Bwght%5D.ttf"
python3 -m fontTools.varLib.instancer "${TMP}/Antonio-VF.ttf" wght=400 \
    -o "${TMP}/Antonio-Regular.ttf"
pyftsubset "${TMP}/Antonio-Regular.ttf" \
    "--unicodes=${COMMON_UNICODES}" \
    "--ignore-missing-unicodes" \
    "--drop-tables+=GPOS,GSUB,DSIG" \
    "--output-file=${ASSETS}/Antonio.ttf"

echo "→ Oswald (Google Fonts main, base cut = wght=400)"
curl -sSL -o "${TMP}/Oswald-VF.ttf" \
    "https://github.com/google/fonts/raw/main/ofl/oswald/Oswald%5Bwght%5D.ttf"
python3 -m fontTools.varLib.instancer "${TMP}/Oswald-VF.ttf" wght=400 \
    -o "${TMP}/Oswald-Regular.ttf"
pyftsubset "${TMP}/Oswald-Regular.ttf" \
    "--unicodes=${COMMON_UNICODES}" \
    "--ignore-missing-unicodes" \
    "--drop-tables+=GPOS,GSUB,DSIG" \
    "--output-file=${ASSETS}/Oswald.ttf"

# OswaldBold is the same axis variable file instantiated at wght=700. The
# current in-tree copy was regenerated by hand; pyftsubset doesn't do the
# instance-pick on its own. Document here and skip — re-do via fonttools
# instancer if the bundled copy drifts.
echo "→ OswaldBold: skipped (manual wght=700 instance — see README)"

echo "→ Inter 4.1 (rsms/inter release zip; base cut = SemiBold)"
curl -sSL -o "${TMP}/Inter-4.1.zip" \
    "https://github.com/rsms/inter/releases/download/v4.1/Inter-4.1.zip"
unzip -q -o "${TMP}/Inter-4.1.zip" -d "${TMP}/inter"
# Release zip flattens extras/ at the archive root — no Inter-4.1/ wrapper.
subset_full "${TMP}/inter/extras/ttf/Inter-SemiBold.ttf" \
    "${ASSETS}/Inter.ttf"
subset_full "${TMP}/inter/extras/ttf/Inter-Bold.ttf" \
    "${ASSETS}/InterBold.ttf"

echo "→ Source Serif 4 (base cut = Semibold)"
curl -sSL -o "${TMP}/SourceSerif4-Semibold.ttf" \
    "https://github.com/adobe-fonts/source-serif/raw/release/TTF/SourceSerif4-Semibold.ttf"
curl -sSL -o "${TMP}/SourceSerif4-Bold.ttf" \
    "https://github.com/adobe-fonts/source-serif/raw/release/TTF/SourceSerif4-Bold.ttf"
subset_full "${TMP}/SourceSerif4-Semibold.ttf" "${ASSETS}/SourceSerif.ttf"
subset_full "${TMP}/SourceSerif4-Bold.ttf"    "${ASSETS}/SourceSerifBold.ttf"

echo "→ Merriweather (SorkinType static TTFs)"
curl -sSL -o "${TMP}/Merriweather-Regular.ttf" \
    "https://github.com/SorkinType/Merriweather/raw/master/fonts/ttf/Merriweather-Regular.ttf"
curl -sSL -o "${TMP}/Merriweather-Bold.ttf" \
    "https://github.com/SorkinType/Merriweather/raw/master/fonts/ttf/Merriweather-Bold.ttf"
subset_full "${TMP}/Merriweather-Regular.ttf" "${ASSETS}/Merriweather.ttf"
subset_full "${TMP}/Merriweather-Bold.ttf"    "${ASSETS}/MerriweatherBold.ttf"

# BitterPro upstream only ships the variable font — instance to wght=600
# (base cut) and wght=700 (bold role) before subsetting. Done this way
# to keep upstream
# provenance verifiable; matches Google Fonts' downstream static workflow.
echo "→ Bitter (BitterPro VF -> instance at wght=600/700 -> subset)"
curl -sSL -o "${TMP}/Bitter-VF.ttf" \
    "https://github.com/solmatas/BitterPro/raw/master/fonts/variable/Bitter%5Bwght%5D.ttf"
python3 -m fontTools.varLib.instancer "${TMP}/Bitter-VF.ttf" wght=600 \
    -o "${TMP}/Bitter-SemiBold.ttf"
python3 -m fontTools.varLib.instancer "${TMP}/Bitter-VF.ttf" wght=700 \
    -o "${TMP}/Bitter-Bold.ttf"
subset_full "${TMP}/Bitter-SemiBold.ttf" "${ASSETS}/Bitter.ttf"
subset_full "${TMP}/Bitter-Bold.ttf"    "${ASSETS}/BitterBold.ttf"

echo "→ Atkinson Hyperlegible (googlefonts/atkinson-hyperlegible)"
curl -sSL -o "${TMP}/AtkinsonHyperlegible-Regular.ttf" \
    "https://github.com/googlefonts/atkinson-hyperlegible/raw/main/fonts/ttf/AtkinsonHyperlegible-Regular.ttf"
curl -sSL -o "${TMP}/AtkinsonHyperlegible-Bold.ttf" \
    "https://github.com/googlefonts/atkinson-hyperlegible/raw/main/fonts/ttf/AtkinsonHyperlegible-Bold.ttf"
subset_full "${TMP}/AtkinsonHyperlegible-Regular.ttf" "${ASSETS}/Atkinson.ttf"
subset_full "${TMP}/AtkinsonHyperlegible-Bold.ttf"    "${ASSETS}/AtkinsonBold.ttf"

echo "→ OpenRunde (lauridskern/open-runde desktop OTFs; base cut = SemiBold)"
curl -sSL -o "${TMP}/OpenRunde-Semibold.otf" \
    "https://raw.githubusercontent.com/lauridskern/open-runde/main/src/desktop/OpenRunde-Semibold.otf"
curl -sSL -o "${TMP}/OpenRunde-Bold.otf" \
    "https://raw.githubusercontent.com/lauridskern/open-runde/main/src/desktop/OpenRunde-Bold.otf"
subset_full "${TMP}/OpenRunde-Semibold.otf" "${ASSETS}/OpenRunde.ttf"
subset_full "${TMP}/OpenRunde-Bold.otf"    "${ASSETS}/OpenRundeBold.ttf"

echo "→ Roboto (Google Fonts VF -> instance at wght=600/700 -> subset)"
curl -sSL -o "${TMP}/Roboto-VF.ttf" \
    "https://github.com/google/fonts/raw/main/ofl/roboto/Roboto%5Bwdth,wght%5D.ttf"
python3 -m fontTools.varLib.instancer "${TMP}/Roboto-VF.ttf" wght=600 \
    -o "${TMP}/Roboto-SemiBold.ttf"
python3 -m fontTools.varLib.instancer "${TMP}/Roboto-VF.ttf" wght=700 \
    -o "${TMP}/Roboto-Bold.ttf"
subset_full "${TMP}/Roboto-SemiBold.ttf" "${ASSETS}/Roboto.ttf"
subset_full "${TMP}/Roboto-Bold.ttf"     "${ASSETS}/RobotoBold.ttf"

echo "→ Noto Sans (Google Fonts VF -> instance at wght=600/700 -> subset)"
curl -sSL -o "${TMP}/NotoSans-VF.ttf" \
    "https://github.com/google/fonts/raw/main/ofl/notosans/NotoSans%5Bwdth,wght%5D.ttf"
python3 -m fontTools.varLib.instancer "${TMP}/NotoSans-VF.ttf" wght=600 \
    -o "${TMP}/NotoSans-SemiBold.ttf"
python3 -m fontTools.varLib.instancer "${TMP}/NotoSans-VF.ttf" wght=700 \
    -o "${TMP}/NotoSans-Bold.ttf"
subset_full "${TMP}/NotoSans-SemiBold.ttf" "${ASSETS}/NotoSans.ttf"
subset_full "${TMP}/NotoSans-Bold.ttf"     "${ASSETS}/NotoSansBold.ttf"

# Ubuntu classic ships Medium instead of SemiBold in upstream static TTFs;
# Medium is the closest weight to our Semibold-vs-Regular A/B decision.
echo "→ Ubuntu (Google Fonts static TTFs; base cut = Medium)"
curl -sSL -o "${TMP}/Ubuntu-Medium.ttf" \
    "https://github.com/google/fonts/raw/main/ufl/ubuntu/Ubuntu-Medium.ttf"
curl -sSL -o "${TMP}/Ubuntu-Bold.ttf" \
    "https://github.com/google/fonts/raw/main/ufl/ubuntu/Ubuntu-Bold.ttf"
subset_full "${TMP}/Ubuntu-Medium.ttf" "${ASSETS}/Ubuntu.ttf"
subset_full "${TMP}/Ubuntu-Bold.ttf"   "${ASSETS}/UbuntuBold.ttf"

echo "→ SatoshiSymbol (from preserved woff2)"
pyftsubset "${ASSETS}/SatoshiSymbol_source.woff2" \
    "--unicodes=U+E000-E00F" \
    "--drop-tables+=GPOS,GSUB,DSIG" \
    "--flavor=" \
    "--output-file=${ASSETS}/SatoshiSymbol.ttf"

echo "→ (optional) apply U+E007 padding patch"
echo "   ${HERE}/patch_satoshi_symbol.py ${ASSETS}/SatoshiSymbol.ttf"
echo
echo "Done. Sizes:"
wc -c "${ASSETS}"/*.ttf | awk '{printf "  %-40s %d B\n", $2, $1}'

# Sanity-check that ₿ (U+20BF) survived the subset for the body fonts
# that should carry it. SatoshiSymbol/MaterialDesignIcons are
# special-purpose (PUA / icon) fonts and are excluded.
echo
echo "Verifying ₿ (U+20BF) presence in regenerated body fonts:"
python3 - "${ASSETS}" <<'PY'
import os, sys
from fontTools.ttLib import TTFont
assets = sys.argv[1]
expected = [
    "Antonio.ttf", "AntonioSemiBold.ttf", "AntonioBold.ttf",
    "Oswald.ttf", "OswaldBold.ttf",
    "Inter.ttf", "InterBold.ttf",
    "SourceSerif.ttf", "SourceSerifBold.ttf",
    "Merriweather.ttf", "MerriweatherBold.ttf",
    "Bitter.ttf", "BitterBold.ttf",
    "Atkinson.ttf", "AtkinsonBold.ttf",
    "OpenRunde.ttf", "OpenRundeBold.ttf",
    "Roboto.ttf", "RobotoBold.ttf",
    "NotoSans.ttf", "NotoSansBold.ttf",
    "Ubuntu.ttf", "UbuntuBold.ttf",
]
missing = []
for name in expected:
    path = os.path.join(assets, name)
    if not os.path.exists(path):
        print(f"  {name:32}  ! file not present")
        continue
    cmap = TTFont(path).getBestCmap()
    if 0x20BF in cmap:
        print(f"  {name:32}  OK  U+20BF -> {cmap[0x20BF]}")
    else:
        print(f"  {name:32}  --  no U+20BF (not in upstream, or stale subset)")
        missing.append(name)
if missing:
    print()
    print(f"NOTE: {len(missing)} font(s) lack U+20BF — either upstream doesn't")
    print("ship the glyph, or the file wasn't refreshed by this script (e.g.")
    print("AntonioSemiBold/AntonioBold/OswaldBold are regenerated out-of-band).")
PY
