#!/usr/bin/env python3
"""Subset Material Design Icons webfont down to a list of named icons.

Why: upstream MDI.ttf is ~1.3 MB (10k+ glyphs). Bundling the whole thing
would bloat LittleFS by a factor of 10 against the rest of the font
assets combined — every icon beyond the three screens we actually paint
would be dead weight. This tool extracts just the glyphs named on the
command line and drops everything else.

Reproducible: the MDI git ref is pinned via --ref (defaults to
`master`); rerunning with the same ref produces byte-identical output
as long as upstream hasn't changed. That preserves the "regen script
diff == upstream diff" invariant the other font regenerators uphold.

Outputs (relative to the repo root):
  - components/fonts/assets/MaterialDesignIcons.ttf
  - components/fonts/include/mdi_codepoints.hpp

Requires: python3.10+, fonttools, curl.
"""
from __future__ import annotations

import argparse
import pathlib
import re
import subprocess
import sys
import tempfile
import textwrap
import urllib.request


REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
ASSETS_DIR = REPO_ROOT / "components" / "fonts" / "assets"
HEADER_PATH = REPO_ROOT / "components" / "fonts" / "include" / "mdi_codepoints.hpp"

UPSTREAM_BASE = "https://raw.githubusercontent.com/Templarian/MaterialDesign-Webfont"

# Matches `.mdi-<name>::before { ... content: "\F1234"; ... }` in the
# upstream CSS. Tolerates unicode escapes of 4-6 hex digits; MDI uses 5.
_ICON_RE = re.compile(
    r"\.mdi-(?P<name>[A-Za-z0-9-]+)::before\s*\{[^}]*?"
    r"content:\s*\"\\(?P<cp>[0-9A-Fa-f]{4,6})\""
)


def fetch(url: str) -> bytes:
    # Fetch once per invocation; no on-disk cache. The regen scripts are
    # developer-run, not CI-run, so saving a few KB is not worth the
    # staleness risk if we ever pin --ref to a tag.
    with urllib.request.urlopen(url, timeout=30) as r:
        return r.read()


def parse_css(css: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for m in _ICON_RE.finditer(css):
        out[m["name"]] = int(m["cp"], 16)
    return out


def build_header(names_to_cp: dict[str, int]) -> str:
    lines = [
        "// Auto-generated by tools/fonts/subset_mdi.py — do NOT edit by hand.",
        "// Regenerate with `tools/fonts/regen_mdi.sh` after changing the",
        "// icon list in that script.",
        "",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace btclock {",
        "namespace mdi {",
        "",
    ]
    for name, cp in sorted(names_to_cp.items()):
        # kIconPickaxe, kIconLightningBolt, kIconRocketLaunch.
        ident = "kIcon" + "".join(
            part.capitalize() for part in name.split("-")
        )
        lines.append(f"inline constexpr std::uint32_t {ident} = 0x{cp:X};  // mdi-{name}")
    lines += [
        "",
        "}  // namespace mdi",
        "}  // namespace btclock",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(
        description="Subset MDI webfont to a handful of named icons.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument(
        "--ref",
        default="master",
        help="MDI-Webfont git ref to download (default: master).",
    )
    ap.add_argument(
        "--out-ttf",
        type=pathlib.Path,
        default=ASSETS_DIR / "MaterialDesignIcons.ttf",
        help="Output subsetted TTF path.",
    )
    ap.add_argument(
        "--out-header",
        type=pathlib.Path,
        default=HEADER_PATH,
        help="Output C++ codepoint header path.",
    )
    ap.add_argument(
        "icons",
        nargs="+",
        help="Icon names WITHOUT the mdi- prefix, e.g. lightning-bolt pickaxe",
    )
    args = ap.parse_args(argv)

    css_url = f"{UPSTREAM_BASE}/{args.ref}/css/materialdesignicons.css"
    ttf_url = f"{UPSTREAM_BASE}/{args.ref}/fonts/materialdesignicons-webfont.ttf"

    print(f"→ fetching CSS {css_url}", file=sys.stderr)
    css = fetch(css_url).decode("utf-8", errors="replace")
    all_icons = parse_css(css)

    wanted: dict[str, int] = {}
    missing: list[str] = []
    for name in args.icons:
        # Allow callers to pass with-or-without the `mdi-` prefix so the
        # tool matches the mental model of the CSS class name.
        stripped = name.removeprefix("mdi-")
        if stripped in all_icons:
            wanted[stripped] = all_icons[stripped]
        else:
            missing.append(name)
    if missing:
        print(
            f"error: icon names not found in upstream CSS: {missing}",
            file=sys.stderr,
        )
        return 2

    cps = sorted(wanted.values())
    print(
        f"→ resolved {len(wanted)} icons: "
        + ", ".join(f"{k}=U+{v:X}" for k, v in wanted.items()),
        file=sys.stderr,
    )

    print(f"→ fetching TTF {ttf_url}", file=sys.stderr)
    ttf_bytes = fetch(ttf_url)

    with tempfile.TemporaryDirectory() as td:
        src_ttf = pathlib.Path(td) / "mdi.ttf"
        src_ttf.write_bytes(ttf_bytes)

        unicodes = ",".join(f"U+{cp:X}" for cp in cps)
        cmd = [
            sys.executable,
            "-m",
            "fontTools.subset",
            str(src_ttf),
            f"--unicodes={unicodes}",
            "--drop-tables+=GPOS,GSUB,DSIG",
            f"--output-file={args.out_ttf}",
        ]
        print("→ " + " ".join(cmd), file=sys.stderr)
        subprocess.run(cmd, check=True)

    args.out_ttf.parent.mkdir(parents=True, exist_ok=True)
    args.out_header.parent.mkdir(parents=True, exist_ok=True)
    args.out_header.write_text(build_header(wanted))
    print(f"→ wrote {args.out_ttf} ({args.out_ttf.stat().st_size} B)", file=sys.stderr)
    print(f"→ wrote {args.out_header}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
