// Mining-pool logo registry.
//
// Small compile-time table keyed by the pool identifier
// `PoolDataSource::pool_name()` emits into DataSnapshot::PoolStats::name.
// Two surfaces:
//
//   * `LookupMeta(name)`           — filename + dimensions for any pool
//                                     known to ship a logo upstream.
//                                     Used by the runtime fetcher
//                                     (`pool_logo_fetcher`) to know
//                                     where to download from and how
//                                     to interpret the header-less
//                                     `<pool>.bin` byte stream.
//   * `Lookup(name)`               — returns a vendored bitmap pointer
//                                     for the small minimal set we
//                                     still ship in `.text` so a
//                                     first-boot or NVS-wiped device
//                                     can paint a logo before WiFi /
//                                     LittleFS comes up. The target
//                                     renderer wraps this with
//                                     `LookupResolved()` (in
//                                     pool_logo_cache.cpp) which
//                                     prefers a fetched cache copy
//                                     under `/lfs/pool_logos/`.
//
// Bitmaps in `pool_logos.cpp` are generated by
// `tools/pool_logos/convert.py` from the `.bin` files in
// https://git.btclock.dev/btclock/mining-pool-logos. The on-disk and
// compile-time formats match: 1-bit-per-pixel MSB-first with
// stride = ceil(width / 8); the upstream files have NO header, so the
// dimensions live in this file's `kLogoMeta` table (and on
// `PoolBase::logo_width()` / `logo_height()` for the fetcher's lookup
// the other direction). The audit in bd btclock_v4-5yi dropped most
// vendored bitmaps to reclaim ~45 KB of `.text`; the metadata stays
// because the cache resolver still needs dimensions to interpret a
// fetched file.

#pragma once

#include <cstddef>
#include <cstdint>
#include <string>

namespace btclock {
namespace pool_logos {

// A vendored pool logo. `bitmap` is a 1-bit-per-pixel MSB-first byte
// array with stride = ceil(width / 8). Semantics match the v3 Arduino
// firmware: a 0 bit is ink (black pixel painted into the framebuffer),
// a 1 bit is background (no pixel painted). `key` is a pointer into
// static .rodata — safe to compare across translation units.
struct PoolLogo {
  const char* key;
  const std::uint8_t* bitmap;
  std::size_t bitmap_size;
  int width;
  int height;
};

// Filename + dimensions for a pool's upstream `.bin`. Returned by
// `LookupMeta`; the fetcher uses `filename` to build the URL and the
// LittleFS cache path, the renderer uses `width`/`height` to interpret
// the raw byte stream (upstream files have no header).
//
// IMPORTANT: this struct is also forward-declared at
// components/pool_logo_fetcher/src/pool_logo_fetcher.cpp because
// components can't include from main/. Both declarations must stay
// byte-identical or the fetcher will read garbage at link time.
struct PoolLogoMeta {
  const char* key;
  const char* filename;
  int width;
  int height;
};

// Case-insensitive lookup against the registry. Returns nullptr when no
// logo is registered for `pool_name`, which the renderer treats as
// "paint the text-split fallback". Empty names always return nullptr.
const PoolLogo* Lookup(const std::string& pool_name);

// Same key fold as `Lookup`, but returns the metadata even for pools
// whose vendored bitmap was dropped in the bd btclock_v4-5yi audit —
// so the runtime fetcher + cache resolver can still resolve a `.bin`
// for them. Returns nullptr for pools that have no logo at all (e.g.
// public_pool, ckpool, satoshi_radio). Empty names return nullptr.
const PoolLogoMeta* LookupMeta(const std::string& pool_name);

// True when there is *any* visual logo available for `pool_name` —
// either a vendored bitmap OR an on-disk cache file under
// `/lfs/pool_logos/`. Host-test paths use the simpler `Lookup() != nullptr`
// because they have no LittleFS; this overload lives in the target-only
// cache TU. Defined as a free function (not a member) so panel-text
// helpers and the renderer can both consume it.
bool HasResolvedLogo(const std::string& pool_name);

// Cache-aware resolver: prefers `/lfs/pool_logos/<file>` over the
// compile-time vendored bitmap, with a one-slot PSRAM-backed in-memory
// cache so the renderer hot path doesn't `fread` every paint.
// Target-only — defined in pool_logo_cache.cpp.
const PoolLogo* LookupResolved(const std::string& pool_name);

// Drop the in-memory cache slot. Called by the
// POST /api/action/clear_pool_logos endpoint after it deletes the
// on-disk `<pool>.bin` files so the next paint won't reuse the
// already-loaded bitmap. Target-only.
void EvictCacheSlot();

// Host-test-only hooks — defined in pool_logo_cache_host.cpp. After
// bd btclock_v4-5yi dropped the last vendored bitmap, host tests need
// a way to mark a synthetic pool name as "has-logo" so the
// `BuildPanelTexts` logo-vs-text branch stays covered without
// requiring a real cached file. Calling these from target code is a
// link error — by design.
void RegisterTestLogo(const std::string& pool_name);
void ClearTestLogos();

}  // namespace pool_logos
}  // namespace btclock
