// Mining-pool logo registry.
//
// Small compile-time table of 1-bpp bitmaps keyed by the pool identifier
// `PoolDataSource::pool_name()` emits into DataSnapshot::PoolStats::name.
// Used by the mining-pool screen renderers to paint a graphical logo on
// the first panel when one is available, with a text-split fallback for
// pools that don't have a vendored bitmap. Mirrors the old btclock_v3_fci
// firmware's per-pool `hasLogo()` / `getLogo()` plumbing, but bakes the
// bitmaps into .text rather than downloading them into LittleFS — keeps
// the dependency-free host test + wasm-preview builds working and
// removes the runtime dependency on an HTTPS logos-server.
//
// Bitmaps are generated by tools/pool_logos/convert.py from the
// `.bin` files in https://git.btclock.dev/btclock/mining-pool-logos,
// committed under main/screens/assets/pool_logos.cpp so regenerating is
// only needed when a logo file changes.

#pragma once

#include <cstddef>
#include <cstdint>
#include <string>

namespace btclock {
namespace pool_logos {

// A vendored pool logo. `bitmap` is a 1-bit-per-pixel MSB-first byte
// array with stride = ceil(width / 8). Semantics match the v3 Arduino
// firmware: a 0 bit is ink (black pixel painted into the framebuffer),
// a 1 bit is background (no pixel painted). `key` is a pointer into
// static .rodata — safe to compare across translation units.
struct PoolLogo {
  const char* key;
  const std::uint8_t* bitmap;
  std::size_t bitmap_size;
  int width;
  int height;
};

// Case-insensitive lookup against the registry. Returns nullptr when no
// logo is registered for `pool_name`, which the renderer treats as
// "paint the text-split fallback". Empty names always return nullptr.
const PoolLogo* Lookup(const std::string& pool_name);

}  // namespace pool_logos
}  // namespace btclock
