// GENERATED by tools/fonts/gen_available_font_catalog.py — DO NOT EDIT.
// Regenerate: python3 tools/fonts/gen_available_font_catalog.py --assets
// components/fonts/assets --out main/app/catalog_available_font_catalog.gen.hpp
#pragma once

#include <array>
#include <cstddef>
#include <string_view>

namespace btclock::catalogs {

struct AvailableFontCatalogEntry {
  std::string_view id;
  bool has_btc_symbol;
};

inline constexpr std::size_t kAvailableFontCatalogCount = 24;

inline constexpr std::array<AvailableFontCatalogEntry,
                            kAvailableFontCatalogCount>
    kAvailableFontCatalog{{
        {"antonio", false},
        {"oswald", false},
        {"inter", true},
        {"sourceSerif", true},
        {"merriweather", true},
        {"bitter", false},
        {"atkinson", false},
        {"antonioSemiBold", false},
        {"antonioBold", false},
        {"oswaldBold", false},
        {"interBold", true},
        {"sourceSerifBold", true},
        {"merriweatherBold", true},
        {"bitterBold", false},
        {"atkinsonBold", false},
        {"openRunde", true},
        {"roboto", false},
        {"robotoBold", false},
        {"notoSans", true},
        {"notoSansBold", true},
        {"ubuntu", false},
        {"ubuntuBold", false},
        {"azeret", true},
        {"azeretSemiBold", true},
    }};

}  // namespace btclock::catalogs
