// Runtime catalogues the WebUI reads from GET /api/settings so its
// drop-downs can list every option this firmware build supports.
//
// All arrays here are `constexpr` (except entries sourced from generated
// font metadata) so adding or removing an entry is a rebuild — there is
// no NVS state that could go stale.
//
// Source-of-truth rules:
//   - Font picker ids + ₿ glyph availability live in
//     catalog_available_font_catalog.gen.hpp — regenerated by
//     tools/fonts/gen_available_font_catalog.py from each bundled TTF's
//     cmap (invoked from tools/fonts/regen.sh after pyftsubset). Keeps
//     GET availableFonts in lock-step with the subset pipeline without a
//     runtime Font probe on every settings GET.
//   - `kAvailableCurrencies`: codes the BTC-price / Moscow-time data
//     source can render. Keep in sync with the currency set the
//     DataHub / price websocket actually populates (main.cpp passes the
//     active subset into ScreenManager).
//   - `kScreenKinds`: derived at compile time from BTCLOCK_SCREEN_KIND_LIST
//     in main/screens/screen_kind.hpp so the enum and the API catalogue
//     can't drift. Only user-rotatable screens live in the list; boot and
//     provisioning UIs are intentionally excluded.
//
#pragma once

#include <array>
#include <cstddef>
#include <string_view>

#include "catalog_available_font_catalog.gen.hpp"
#include "screens/screen_kind.hpp"

namespace btclock {
namespace catalogs {

// ISO 4217 codes the price / moscow-time / market-cap screens can
// render. Must stay in lock-step with the upstream price websocket
// (ws.btclock.dev/api/v2/currencies) — advertising codes the backend
// doesn't actually publish leaves the WebUI's picker showing options
// that never produce a price tick. settings_api's GET drops any legacy
// `actCurrencies` entries that fall outside this set, and PATCH silently
// skips unknown codes, so shrinking this list is safe for upgrades.
inline constexpr std::array<std::string_view, 7> kAvailableCurrencies = {
    "USD", "EUR", "GBP", "CAD", "CHF", "AUD", "JPY",
};

// One entry per rotatable screen. `api_id` is what gets serialised into
// `screens[].id` and what NVS keys like `screen<id>Visible` use.
struct ScreenKind {
  int api_id;
  std::string_view short_name;     // log tag (KindName())
  std::string_view display_label;  // WebUI-facing human name
};

// Expand the X-macro into a std::array. Using string_view so the array
// is header-only constexpr without forcing a .cpp translation unit.
inline constexpr auto kScreenKinds = [] {
#define BTCLOCK_SCREEN_KIND_COUNT_ENTRY(enum_name, api_id, short_name, label) +1
  constexpr std::size_t kCount =
      0 BTCLOCK_SCREEN_KIND_LIST(BTCLOCK_SCREEN_KIND_COUNT_ENTRY);
#undef BTCLOCK_SCREEN_KIND_COUNT_ENTRY
  std::array<ScreenKind, kCount> arr{};
  std::size_t i = 0;
#define BTCLOCK_SCREEN_KIND_EMIT_ENTRY(enum_name, api_id, short_name, label) \
  arr[i++] = ScreenKind{(api_id), (short_name), (label)};
  BTCLOCK_SCREEN_KIND_LIST(BTCLOCK_SCREEN_KIND_EMIT_ENTRY)
#undef BTCLOCK_SCREEN_KIND_EMIT_ENTRY
  return arr;
}();

}  // namespace catalogs
}  // namespace btclock
