#!/usr/bin/env python3
# Emit a C++ source file with each TTF baked in as a byte array, plus
# its size constant. Consumed by the emscripten build (tools/wasm/
# build.sh): on device the same symbols come from ESP-IDF EMBED_FILES,
# but that machinery isn't available to the host toolchain. Gated in
# components/fonts/include/font.hpp by BTCLOCK_WASM_BUILD.
import os
import sys

FONTS = [
    ("Antonio.ttf", "kAntonioTtf", "kAntonioTtfSize"),
    ("AntonioSemiBold.ttf", "kAntonioSemiBoldTtf", "kAntonioSemiBoldTtfSize"),
    ("AntonioBold.ttf", "kAntonioBoldTtf", "kAntonioBoldTtfSize"),
    ("Oswald.ttf", "kOswaldTtf", "kOswaldTtfSize"),
    ("OswaldBold.ttf", "kOswaldBoldTtf", "kOswaldBoldTtfSize"),
    ("Inter.ttf", "kInterTtf", "kInterTtfSize"),
    ("InterBold.ttf", "kInterBoldTtf", "kInterBoldTtfSize"),
    ("OpenRunde.ttf", "kOpenRundeTtf", "kOpenRundeTtfSize"),
    ("OpenRundeBold.ttf", "kOpenRundeBoldTtf", "kOpenRundeBoldTtfSize"),
    ("SourceSerif.ttf", "kSourceSerifTtf", "kSourceSerifTtfSize"),
    ("SourceSerifBold.ttf", "kSourceSerifBoldTtf",
     "kSourceSerifBoldTtfSize"),
    ("Merriweather.ttf", "kMerriweatherTtf", "kMerriweatherTtfSize"),
    ("MerriweatherBold.ttf", "kMerriweatherBoldTtf",
     "kMerriweatherBoldTtfSize"),
    ("Bitter.ttf", "kBitterTtf", "kBitterTtfSize"),
    ("BitterBold.ttf", "kBitterBoldTtf", "kBitterBoldTtfSize"),
    ("Atkinson.ttf", "kAtkinsonTtf", "kAtkinsonTtfSize"),
    ("AtkinsonBold.ttf", "kAtkinsonBoldTtf", "kAtkinsonBoldTtfSize"),
    ("SatoshiSymbol.ttf", "kSatoshiSymbolTtf", "kSatoshiSymbolTtfSize"),
    ("MaterialDesignIcons.ttf", "kMaterialDesignIconsTtf",
     "kMaterialDesignIconsTtfSize"),
]


def emit_blob(fp, path, arr_name, size_name):
    with open(path, "rb") as f:
        data = f.read()
    n = len(data)
    fp.write(f"// --- {os.path.basename(path)} ({n} bytes) ---\n")
    fp.write(f"extern const std::uint8_t {arr_name}[{n}];\n")
    fp.write(f"extern const std::size_t {size_name};\n")
    fp.write(f"const std::uint8_t {arr_name}[{n}] = {{\n")
    # 16 bytes per line.
    for i in range(0, n, 16):
        chunk = data[i:i + 16]
        fp.write("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
    fp.write("};\n")
    fp.write(f"const std::size_t {size_name} = {n};\n\n")


def main():
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <assets_dir> <out_cpp>", file=sys.stderr)
        return 2
    assets_dir, out_cpp = sys.argv[1], sys.argv[2]
    out_dir = os.path.dirname(out_cpp)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    with open(out_cpp, "w") as fp:
        fp.write(
            "// AUTOGENERATED by tools/wasm/gen_font_blobs.py\n"
            "// Do not edit by hand — rerun build.sh to regenerate.\n\n"
            "#include <cstddef>\n"
            "#include <cstdint>\n\n"
            "namespace btclock {\n\n"
        )
        for fn, arr, sz in FONTS:
            emit_blob(fp, os.path.join(assets_dir, fn), arr, sz)
        fp.write("}  // namespace btclock\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
