#pragma once

#include <cstdint>
#include <functional>

#include "esp_err.h"
#include "freertos/FreeRTOS.h"
#include "freertos/queue.h"
#include "freertos/task.h"
#include "mcp23017.hpp"

namespace btclock {

// Logical identifier for each of the four BTClock tactile buttons.
// Wired to MCP23017 #1, pins 0..3 (GPA0..GPA3), active-low w/ pull-ups.
enum class ButtonId : uint8_t { k0 = 0, k1 = 1, k2 = 2, k3 = 3 };

// Event kinds generated by ButtonReader.
enum class ButtonEvent : uint8_t { kClick, kLongPress };

// POD event pushed onto the caller-owned FreeRTOS queue. The queue's
// item size must be sizeof(ButtonInput).
struct ButtonInput {
  ButtonId id;
  ButtonEvent event;
};

// Polls the primary MCP23017, debounces the four lower pins, and emits
// click / long-press events onto a caller-owned queue.
//
// Typical usage:
//   auto q = xQueueCreate(8, sizeof(btclock::ButtonInput));
//   btclock::ButtonReader reader(mcp, q);
//   reader.Start();
//
// Posts to `queue` are non-blocking (drop-if-full); losing a burst of
// clicks is preferable to stalling the polling task.
class ButtonReader {
 public:
  // `mcp` must outlive this object. `queue` is owned by the caller and
  // must accept items of size sizeof(ButtonInput).
  ButtonReader(Mcp23017& mcp, QueueHandle_t queue);
  ~ButtonReader();

  ButtonReader(const ButtonReader&) = delete;
  ButtonReader& operator=(const ButtonReader&) = delete;

  // Spawns the background polling task. Safe to call once.
  esp_err_t Start();

  // Default mapping is physical pin `i` → `ButtonId(kNumButtons - 1 - i)`.
  // SetInverted(true) flips it to the raw `i` ordering for users running
  // with the enclosure upside-down. Honours the `inverseButtons` user
  // pref. Read once at boot — caller sets this before Start(); a live
  // PATCH requires a reboot to take effect, matching the SETTINGS.md row.
  //
  // Physical-to-logical mapping reference (the device labels its
  // buttons 1..4 — the labels are the user-facing names, NOT the
  // ButtonId index — `button 1` on the front of the device is logical
  // `ButtonId::k0`). The MCP pin that backs it depends on inversion:
  //
  //   user label   ButtonId   MCP pin (inverseButtons=false)
  //   ----------   --------   ------------------------------
  //   button 1     k0         GPA3
  //   button 2     k1         GPA2
  //   button 3     k2         GPA1
  //   button 4     k3         GPA0
  //
  //   inverseButtons=true flips the MCP-pin column: button 1 → GPA0,
  //   button 2 → GPA1, ..., button 4 → GPA3.
  //
  // event_loop.cpp's click semantics line up with the user numbering:
  // k0 (button 1) = pause/resume; k1 (button 2) = next screen;
  // k2 (button 3) = prev screen;  k3 (button 4) = debug overlay.
  // Long-press on k0 (button 1) toggles the manual DND override.
  // The boot-time wifi-reset hold also reads the physical button 1
  // pin (see app/boot/init_wifi_reset_button.cpp).
  void SetInverted(bool inverted) { inverted_ = inverted; }

  // Install a one-shot callback fired when all four MCP1 buttons
  // (pins 0..3) are simultaneously held for 5 s. Used as the
  // factory-reset hardware trigger so a user can wipe NVS without a
  // working WiFi/WebUI. The callback runs on the poll task; keep it
  // non-blocking or post work onto another task. Fires at most once
  // per continuous hold — the detector re-arms only after at least
  // one of the four buttons is released. Safe to call before or
  // after Start(); a null callback disables the detector.
  void SetOnAllButtonsLongPress(std::function<void()> cb) {
    all_long_press_cb_ = std::move(cb);
  }

 private:
  static constexpr uint8_t kNumButtons = 4;

  // Per-button debounce / timing state.
  struct State {
    // Raw level last seen on this pin (true = electrical HIGH = released).
    bool last_raw = true;
    // How many consecutive 20 ms samples the raw level has persisted.
    uint8_t stable_ticks = 0;
    // The debounced logical state (true = pressed).
    bool pressed = false;
    // Tick count since the debounced press started (only valid while
    // pressed). Saturates so it can't wrap during a very long hold.
    uint16_t press_ticks = 0;
    // Set once we've already emitted kLongPress for the current hold so
    // we don't fire it twice, and so the matching release won't emit
    // kClick.
    bool long_fired = false;
  };

  static void TaskTrampoline(void* arg);
  void Run();

  Mcp23017& mcp_;
  QueueHandle_t queue_;
  TaskHandle_t task_ = nullptr;
  volatile bool stop_ = false;
  State state_[kNumButtons]{};
  // All-buttons-held detector state. Incremented only while every
  // entry in `state_` reports .pressed; resets to 0 on any release.
  // Saturates so a very long hold can't wrap. `all_long_fired_`
  // prevents the callback firing a second time during one continuous
  // hold — the user has to release at least one button to re-arm.
  uint32_t all_pressed_ticks_ = 0;
  bool all_long_fired_ = false;
  std::function<void()> all_long_press_cb_;
  // Set by SetInverted(); see comment there.
  bool inverted_ = false;
};

}  // namespace btclock
