// Compact IANA-name -> POSIX TZ string lookup, plus a thin wrapper
// around setenv("TZ", ...)/tzset() and an NVS-backed persistence layer.
//
// Rationale: ESP-IDF v5.5's newlib ships POSIX TZ string support but no
// zoneinfo database. The production Arduino firmware already carries a
// compact table mapping ~484 IANA zone IDs (e.g. "Europe/Amsterdam") to
// ~93 unique POSIX strings (e.g. "CET-1CEST,M3.5.0,M10.5.0/3"). We port
// that same table so user-visible behaviour matches byte-for-byte, and
// the existing WebUI's dropdown values keep working unchanged when
// pointed at the BTClock v4 control-server.
//
// The table lives in components/timezone/include/timezone/
// tz_table_generated.hpp, auto-generated by
// tools/timezone/generate_tz_table.py.

#pragma once

#include <string>
#include <string_view>

#include "timezone/tz_table_generated.hpp"

#ifdef __has_include
#if __has_include("esp_err.h")
#include "esp_err.h"
#define BTCLOCK_TZ_HAS_ESP_ERR 1
#endif
#endif

#ifndef BTCLOCK_TZ_HAS_ESP_ERR
// Host build: mirror the tiny esp_err_t surface we actually use. The
// values match ESP-IDF's esp_err_t.h so tests can compare numerically.
using esp_err_t = int;
inline constexpr esp_err_t ESP_OK = 0;
inline constexpr esp_err_t ESP_FAIL = -1;
inline constexpr esp_err_t ESP_ERR_INVALID_ARG = 0x102;
inline constexpr esp_err_t ESP_ERR_NOT_FOUND = 0x105;
#endif

namespace btclock::timezone {

// NVS namespace + key for the persisted IANA name. Kept as constexpr
// strings so callers (and tests) can reference them without depending
// on the implementation file.
inline constexpr const char* kNvsNamespace = "time";
inline constexpr const char* kNvsKey = "tz";

// The WebUI-facing settings subsystem persists the same IANA name under
// the "settings" namespace as `tzString` (matches the old firmware's
// Preferences layout). GetTimezoneName() prefers this location so a
// PATCH /api/settings that sets `tzString` takes effect on next boot
// without needing a second write into the legacy "time" namespace.
inline constexpr const char* kSettingsNamespace = "settings";
inline constexpr const char* kSettingsKey = "tzString";

// Fallback IANA zone when the stored value is missing or unknown.
inline constexpr const char* kDefaultZone = "UTC";

// Look up the POSIX TZ string for an IANA zone identifier. Returns an
// empty string_view when the zone is unknown — callers should either
// surface the error or fall back to "UTC0".
//
// Inline + constexpr so the host test suite can use this without
// pulling in the ESP-IDF-only .cpp (which needs NVS).
constexpr std::string_view PosixForIana(std::string_view iana_name) {
  for (const auto& entry : kTzTable) {
    if (entry.first == iana_name) return entry.second;
  }
  return {};
}

// Set the process-wide timezone by IANA name:
//   - Look up the POSIX string.
//   - setenv("TZ", <posix>, 1); tzset();
// On success, writes the IANA name into NVS so the next boot restores
// it automatically. Returns ESP_ERR_NOT_FOUND for unknown names,
// ESP_ERR_INVALID_ARG for null/empty input, or whatever the NVS layer
// reports if persistence fails (the env var is still set regardless).
esp_err_t SetTimezoneByName(const char* iana_name);

// Current IANA zone — reads NVS (namespace "time", key "tz"); returns
// kDefaultZone when the key is missing/empty. Never touches the
// environment; intentionally side-effect-free for callers that just
// want to report status.
std::string GetTimezoneName();

// One-shot boot init: read NVS, call SetTimezoneByName, log the chosen
// zone. Safe to call before WiFi/SNTP come up — setenv/tzset don't
// need the network.
void InitFromNvs();

}  // namespace btclock::timezone
