#!/usr/bin/env python3
"""Generate the BTClock v4 timezone lookup table.

Reads the upstream Arduino firmware's ``include/timezone_data.hpp`` —
whose ``TIMEZONE_DATA`` array maps ~484 IANA zone IDs to a compact
``TimezoneValue`` enum, and whose ``get_timezone_value_string`` switch
maps each enum value to a POSIX TZ string — and flattens both into a
single ``constexpr std::array<std::pair<std::string_view,
std::string_view>, N>`` that the firmware consumes directly.

The output is committed to the tree (``components/timezone/include/
timezone/tz_table_generated.hpp``) so the build does not need Python
at compile time. Re-run this script whenever the upstream firmware
regenerates its own table:

    python3 tools/timezone/generate_tz_table.py

No dependencies beyond the stdlib.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
SRC_HEADER = REPO_ROOT / "include" / "timezone_data.hpp"
OUT_HEADER = (
    REPO_ROOT
    / "btclock_v4"
    / "components"
    / "timezone"
    / "include"
    / "timezone"
    / "tz_table_generated.hpp"
)


ENTRY_RE = re.compile(
    r'^\s*\{"(?P<name>[^"]+)",\s*TimezoneValue::(?P<value>[A-Za-z0-9_]+)\}\s*,',
    re.MULTILINE,
)
POSIX_RE = re.compile(
    r'case\s+TimezoneValue::(?P<value>[A-Za-z0-9_]+):\s*'
    r'return\s+String\("(?P<posix>[^"]*)"\);'
)


def parse_source(header_text: str) -> list[tuple[str, str]]:
    """Return [(iana_name, posix_tz)], sorted case-insensitively by name."""
    enum_to_posix: dict[str, str] = {}
    for m in POSIX_RE.finditer(header_text):
        enum_to_posix[m.group("value")] = m.group("posix")
    if not enum_to_posix:
        raise SystemExit("error: found zero POSIX entries in source header")

    entries: list[tuple[str, str]] = []
    for m in ENTRY_RE.finditer(header_text):
        name = m.group("name")
        value = m.group("value")
        posix = enum_to_posix.get(value)
        if posix is None:
            raise SystemExit(
                f"error: zone '{name}' references unknown enum {value}"
            )
        entries.append((name, posix))

    if not entries:
        raise SystemExit("error: found zero zone entries in source header")

    # Deduplicate identical (name -> posix) collisions — defensive.
    seen: dict[str, str] = {}
    for name, posix in entries:
        if name in seen and seen[name] != posix:
            raise SystemExit(
                f"error: conflicting posix for '{name}': "
                f"'{seen[name]}' vs '{posix}'"
            )
        seen[name] = posix

    # Sort by IANA name, case-sensitive so binary search works with a
    # byte-wise comparator on the target (we do a linear scan today,
    # but keep the table deterministic for future bsearch).
    return sorted(seen.items(), key=lambda kv: kv[0])


def render_header(entries: list[tuple[str, str]]) -> str:
    posix_set: dict[str, None] = {}
    for _, posix in entries:
        posix_set[posix] = None

    lines: list[str] = []
    lines.append("// Auto-generated by tools/timezone/"
                 "generate_tz_table.py — do not edit by hand.")
    lines.append("// Source of truth: include/timezone_data.hpp (top-level "
                 "firmware tree).")
    lines.append("//")
    lines.append(f"// Zones:  {len(entries)}")
    lines.append(f"// Unique POSIX strings: {len(posix_set)}")
    lines.append("")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <array>")
    lines.append("#include <string_view>")
    lines.append("#include <utility>")
    lines.append("")
    lines.append("namespace btclock::timezone {")
    lines.append("")
    lines.append("using TzEntry = std::pair<std::string_view, std::string_view>;")
    lines.append("")
    lines.append(f"inline constexpr std::array<TzEntry, {len(entries)}> "
                 "kTzTable = {{")
    for name, posix in entries:
        # Escape double quotes and backslashes defensively; the current
        # source has neither but be robust for future edits.
        ne = name.replace("\\", "\\\\").replace('"', '\\"')
        pe = posix.replace("\\", "\\\\").replace('"', '\\"')
        lines.append(f'    {{"{ne}", "{pe}"}},')
    lines.append("}};")
    lines.append("")
    lines.append("}  // namespace btclock::timezone")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not SRC_HEADER.exists():
        print(f"error: source header not found: {SRC_HEADER}", file=sys.stderr)
        return 1
    header_text = SRC_HEADER.read_text(encoding="utf-8")
    entries = parse_source(header_text)
    out = render_header(entries)
    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    OUT_HEADER.write_text(out, encoding="utf-8")
    print(f"wrote {OUT_HEADER.relative_to(REPO_ROOT)} "
          f"({len(entries)} zones)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
