// Auto-generated by tools/fonts/subset_mdi.py — do NOT edit by hand.
// Regenerate with `tools/fonts/regen_mdi.sh` after changing the
// icon list in that script.

#pragma once

#include <cstdint>

namespace btclock {
namespace mdi {

inline constexpr std::uint32_t kIconAlarm = 0xF0020;  // mdi-alarm
inline constexpr std::uint32_t kIconArrowDownBold =
    0xF072E;  // mdi-arrow-down-bold
inline constexpr std::uint32_t kIconArrowUpBold = 0xF0737;  // mdi-arrow-up-bold
inline constexpr std::uint32_t kIconBell = 0xF009A;         // mdi-bell
inline constexpr std::uint32_t kIconBitcoin = 0xF0813;      // mdi-bitcoin
inline constexpr std::uint32_t kIconClockOutline =
    0xF0150;                                                // mdi-clock-outline
inline constexpr std::uint32_t kIconCurrencyBtc = 0xF01AC;  // mdi-currency-btc
inline constexpr std::uint32_t kIconLightningBolt =
    0xF140B;                                            // mdi-lightning-bolt
inline constexpr std::uint32_t kIconPickaxe = 0xF08B7;  // mdi-pickaxe
inline constexpr std::uint32_t kIconRocketLaunch =
    0xF14DE;                                              // mdi-rocket-launch
inline constexpr std::uint32_t kIconWifi = 0xF05A9;       // mdi-wifi
inline constexpr std::uint32_t kIconWifiAlert = 0xF16B5;  // mdi-wifi-alert
inline constexpr std::uint32_t kIconWifiOff = 0xF05AA;    // mdi-wifi-off

}  // namespace mdi
}  // namespace btclock
