// Auto-generated by tools/fonts/subset_mdi.py — do NOT edit by hand.
// Regenerate with `tools/fonts/regen_mdi.sh` after changing the
// icon list in that script.

#pragma once

#include <cstdint>

namespace btclock {
namespace mdi {

inline constexpr std::uint32_t kIconArrowDownBold = 0xF072E;  // mdi-arrow-down-bold
inline constexpr std::uint32_t kIconArrowUpBold = 0xF0737;  // mdi-arrow-up-bold
inline constexpr std::uint32_t kIconLightningBolt = 0xF140B;  // mdi-lightning-bolt
inline constexpr std::uint32_t kIconPickaxe = 0xF08B7;  // mdi-pickaxe
inline constexpr std::uint32_t kIconRocketLaunch = 0xF14DE;  // mdi-rocket-launch

}  // namespace mdi
}  // namespace btclock
